version: "3.9"
services:
  api:
    build: .
    container_name: santander-api
    ports:
      - "8080:8080"
    environment:
      - JAVA_TOOL_OPTIONS=-XX:+UseContainerSupport
    restart: unless-stopped
